- name: command vs shell
  hosts: localhost
  tasks:
  - name: command module
    ansible.builtin.command:  "echo 'Hi, this is from command module' > /tmp/command.txt "

  - name: shell module
    ansible.builtin.shell:  "echo 'Hi, this is from shell module' > /tmp/shell.txt "
# simple command without the need of shell varibale , env and features like redirections ,pipe & go for command module.

# if we need to run complex command or script go for shell module

#Whatever works in command module it will works in shell module, but vice versa is not true/
