- name: configure db server
  hosts: db
  become: yes
  vars:
    login_host: db.aws79s.online
  tasks:
  - name: install MYSQL Server
    ansible.builtin.dnf:
      name: mysql-server
      state: latest

  - name: start and Enable MYSQL server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
  - name: install python mysql dependencies
    ansible.builtin.service:
      name:
      - PyMySQL
      - cryptography
      executable: pip3.9

# check password is already setup or not
  - name: check DB connection
    community.mysql.mysql_info:
      login_user: root
      login_password: ExpenseApp@1
      login_host: "{{ login_host }}"
      filter: version
    ignore_errors: yes
    register: mysql_connection_output

  - name: print output
    ansible.builtin.debug:
      msg: "Output: {{mysql_connection_output }} "
